### ISSUE TITLE
Add ACCESS-ESM1.6 SBD

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/spack-packages#140]
I would like to add an initial SBD for ACCESS-ESM1.6. For now, the only difference from the ACCESS-ESM1.5 SBD will be the MOM5 spec.

In ACCESS-ESM1.6, I would like to build MOM5 in the same way as ACCESS-ESM1.5, except **using the "master" branch and the "ACCESS-ESM" "type" variant**. To allow this, the following changes are required:

In MOM5 SPD:
- Add an "access-esm1.6" version that uses the "master" branch
- Remove the [`conditional` logic](https://github.com/ACCESS-NRI/spack-packages/blob/3f45685e8f4b2e10d03db5bcd0027bc22df475a4/packages/mom5/package.py#L32) from the definition of the "type" variant
- Extend `with`s and `if`s currently set up for `@access-esm1.5` to include `@access-esm1.6`

In ACCESS-ESM1.5 SPD:
- Specify `+type=ACCESS-CM` in MOM5 spec

In (new) ACCESS-ESM1.6 SPD:
- Specify `+type=ACCESS-ESM` in MOM5 spec

I'll follow up with a PR shortly.

**Comment by CodeGat** [comment]
References https://github.com/ACCESS-NRI/ACCESS-ESM1.6/issues/1
