### ISSUE TITLE
Add package for fiat

### ISSUE THREAD

**Issue by penguian** [ACCESS-NRI/spack-packages#147]
The [Spack builtin fiat package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/fiat/package.py) uses the upstream [ecmwf-ifs/fiat](https://github.com/ecmwf-ifs/fiat) repository.

The [ACCESS-NRI/fiat](https://github.com/ACCESS-NRI/fiat) package includes `um` and `calltrace` branches based on  [MartinDix/fiat](https://github.com/MartinDix/fiat). 

Add a package for fiat based on the [Spack builtin package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/fiat/package.py) but using the  [ACCESS-NRI/fiat](https://github.com/ACCESS-NRI/fiat) branches.

**Comment by aidanheerdegen** [comment]
> Add a package for fiat based on the [Spack builtin package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/fiat/package.py) but using the [ACCESS-NRI/fiat](https://github.com/ACCESS-NRI/fiat) branches.

Just curious: do we need to have a fork of `fiat` to make local changes?
