### ISSUE TITLE
Spack package for ACCESS-ESM1.5

### ISSUE THREAD

**Issue by penguian** [ACCESS-NRI/spack-packages#59]
Create a Spack package for ACCESS-ESM1.5 loosely based on the `Makefile` in https://github.com/penguian/access-esm-build-gadi . That `Makefile` uses the following repositories on GitHub:

- [ACCESS-NRI/cice4](https://github.com/ACCESS-NRI/cice4)
- [ACCESS-NRI/GCOM](https://github.com/ACCESS-NRI/GCOM)(private)
- [ACCESS-NRI/UM_v7](https://github.com/ACCESS-NRI/UM_v7) (private)
- [coecms/dummygrib](https://github.com/coecms/dummygrib)
- [coecms/oasis3-mct](https://github.com/coecms/oasis3-mct)
- [OceansAus/ACCESS-ESM1.5-MOM5](https://github.com/COSIMA/ACCESS-ESM1.5-MOM5)

as well as the following NCI modules:
- intel-compiler/2019.3.199
- intel-mkl/2019.3.199
- netcdf/4.7.1
- openmpi/4.0.2

and the following modules from `~access/modules`:
- fcm/2019.09.0
- um 

The ACCESS-NRI/cice4, ACCESS-NRI/GCOM, and ACCESS-NRI/UM_v7 repositories are new and are subject to change.

**Comment by harshula** [comment]
Existing FCM and GCOM SPDs:
* https://github.com/ACCESS-NRI/spack-packages/tree/main/packages/fcm
* https://github.com/ACCESS-NRI/spack-packages/tree/main/packages/gcom

**Comment by penguian** [comment]
The [`gcom`]( https://github.com/ACCESS-NRI/spack-packages/tree/main/packages/gcom) package build is sufficiently different from the build needed for ESM1.5 that I think that there should be a `gcom4` package:

- The `gcom` package uses the MOSRS `gcom` repository mirror at `file:///g/data/ki32/mosrs/gcom/main/trunk`. The oldest GCOM version in the MOSRS repository is vn4.8 at revision 1. The oldest NCI config that I could find in that repository is at [`branches/dev/martindix/vn5.1_nci_config` ](https://code.metoffice.gov.uk/trac/gcom/browser/main/branches/dev/martindix/vn5.1_nci_config) for vn5.1.
- The ESM 1.5 build that I have created at https://github.com/penguian/access-esm-build-gadi/blob/master/Makefile uses the   vn4.5 NCI config at https://github.com/ACCESS-NRI/GCOM/tree/dev/Share/gcom4.5_access_config 
- Neither of these NCI configurations uses the same machine configuration as the current (vn8.3+) configuration at https://code.metoffice.gov.uk/trac/gcom/browser/main/trunk/fcm-make/machines/nci_gadi_ifort_mpp.cfg
  - vn5.1: https://code.metoffice.gov.uk/trac/gcom/browser/main/branches/dev/martindix/vn5.1_nci_config/fcm-make/machines/nci_raijin_ifort_mpp.cfg
  - vn4.5: https://github.com/ACCESS-NRI/GCOM/blob/dev/Share/gcom4.5_access_config/fcm-make/machines/nci_ifort_openmpi.cfg

**Comment by penguian** [comment]
Is there any requirement for the ACCESS-ESM1.5 Spack package to build with the `gcc` compilers? Specifically, the [gcom4](https://github.com/ACCESS-NRI/spack-packages/blob/main/packages/gcom4/package.py)  package build at version 4.5 does not support `gcc`. See also Issue #85

**Comment by harshula** [comment]
Naming of the SBD/SPD is constrained by:
https://spack.readthedocs.io/en/latest/packaging_guide.html#package-names
`Spack uses the directory name as the package name in order to give packagers more freedom in naming their packages. Package names can contain letters, numbers, and dashes.`

https://spack.readthedocs.io/en/latest/packaging_guide.html#package-class-names
`Spack loads package.py files dynamically, and it needs to find a special class name in the file for the load to succeed. The class name (Libelf in our example) is formed by converting words separated by - in the file name to CamelCase. If the name starts with a number, we prefix the class name with _. `

**Comment by harshula** [comment]
The SBD has been merged: https://github.com/ACCESS-NRI/spack-packages/blob/main/packages/access-esm1p5/package.py
