### ISSUE TITLE
nci-openmpi: use env.append_flags() instead of env.append_path()

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/spack-packages#62]
Hi @ScottWales ,

Is there any particular reason that you used `env.append_path()`:
```
        env.append_path("OMPI_FCFLAGS", "-I" + finc_path)
        env.append_path("OMPI_LDFLAGS", "-L" + self.prefix.lib + " -L" + flib_path)
```
instead of `env.append_flags()`? @aidanheerdegen pointed this out in https://github.com/ACCESS-NRI/spack-packages/issues/61#issuecomment-1931047657 . I'm planning on changing it to `env.append_flags()`.

**Comment by ScottWales** [comment]
It's possibly a bug, or possibly to do with CMAKE's strange list behaviour I don't recall. `append_flags()` sounds like a better call to use if it doesn't have issues.
