### ISSUE TITLE
mom5: BGC variant required

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/spack-packages#71]
A prerequisite to support biogeochemistry (BGC) model configurations is a build of MOM5 with BGC enabled. In this case the BGC component is called WOMBAT.

The build script requires a `type` of `ACCESS-OM-BGC` which then enables a CPP preprocessor flag:

https://github.com/mom-ocean/MOM5/blob/master/exp/MOM_compile.csh#L108-L109

We need a MOM5 variant that builds the `ACCESS-OM-BGC` version of the MOM5 model. See this issue for more background information

https://github.com/ACCESS-NRI/access-om2-configs/issues/16#issuecomment-1970819902

**Comment by harshula** [comment]
Hi @aidanheerdegen ,

I've added support for the following in the development branch:
https://github.com/mom-ocean/MOM5/blob/d7ba13a3f364ce130b6ad0ba813f01832cada7a2/exp/MOM_compile.csh#L104-L114

Do you want me to add support for all these `type`'s?
https://github.com/mom-ocean/MOM5/blob/d7ba13a3f364ce130b6ad0ba813f01832cada7a2/exp/MOM_compile.csh#L49-L61

**Comment by aidanheerdegen** [comment]
There is value in having `MOM_solo` in addition to the ACCESS models. 

The others we don’t use and so won’t test and can’t guarantee if they work or not. For that reason I’d be happy to leave out EBM (Energy Balance Model) as well. It is a very special case.
