### ISSUE TITLE
Spack package for cice4

### ISSUE THREAD

**Issue by penguian** [ACCESS-NRI/spack-packages#87]
Create a Spack package for `cice4` based on  [ACCESS-NRI/cice4](https://github.com/ACCESS-NRI/cice4) and [cice5](https://github.com/ACCESS-NRI/spack-packages/blob/main/packages/cice5/package.py).

The `Makefile` in https://github.com/penguian/access-esm-build-gadi uses the  [ACCESS-NRI/cice4](https://github.com/ACCESS-NRI/cice4) repository on GitHub to build CICE4.1 for ACCESS-ESM1.5.

**Comment by aidanheerdegen** [comment]
Definitely talk with @harshula as he had this down as something to look into.
